package com.dbclm.nace.data.entity;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import io.swagger.annotations.ApiModelProperty;


@Entity
@Table(name = "NACE_DETAILS")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class NaceDetails {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "autogenerated id")
	private Long id;

	@ApiModelProperty(value = "nace-code")
	private String code;
	
	@ApiModelProperty(value = "nace-parent")
	private String parent;
	
	@ApiModelProperty(value = "nace-description")
	private String description;
	
	@ApiModelProperty(value = "nace-orderNumber")
	private String orderNumber;
	
	@ApiModelProperty(value = "nace-level")
	private Integer level;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getParent() {
		return parent;
	}
	public void setParent(String parent) {
		this.parent = parent;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getorderNumber() {
		return orderNumber;
	}
	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}
	public Integer getLevel() {
		return level;
	}
	public void setLevel(Integer level) {
		this.level = level;
	}
	
}
